name: '$(Build.DefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)'
trigger:
  branches:
    include:
    - master
parameters:

- name: TerraformState
  displayName: TerraformState
  type: string
  default: apply
  values:
  - init
  - apply
  - plan
  - destroy

pool:
  name: 'Azure Pipelines'
#  demands:
#  - agent.name -equals GX-ZWEAPPPWV134-Agent2
variables:
- group: ACCESS_DETAILS

stages:
- stage: BuildApp
  jobs:
  - job: TerraformBuild
    steps:
    # - task: 30f35852-3f7e-4c0c-9a88-e127b4f97211@1
    #   condition: false
    #   inputs:
    #     alias: none
    - task: CopyFiles@2
      inputs:
        Contents: '*.tf'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace tokens in **/*.tf'
      inputs:
        rootDirectory: '$(Build.ArtifactStagingDirectory)'
        targetFiles: |
         *.tf
        tokenPrefix: '__'
        tokenSuffix: '__'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop