# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'home_windows'

variables:
- group: ACCESS_DETAILS

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.13.3'

- task: TerraformTaskV2-INIT@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure Pass - Sponsorship(6b0b3e01-c26a-4b1e-8433-e649fc0a71ec)'
    backendAzureRmResourceGroupName: 'terraform'
    backendAzureRmStorageAccountName: 'terraformstorage1001'
    backendAzureRmContainerName: 'terraformwebapp'
    backendAzureRmKey: 'tf/terraform.tfstate'
    commandOptions: -input=false -var "client_id=$(TF_VAR_client_id) client_secret=$(TF_VAR_client_secret) subscription_id=$(TF_VAR_subscription_id) tenant_id=$(TF_VAR_tenant_id)"

- task: TerraformTaskV2-PLAN@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure Pass - Sponsorship(6b0b3e01-c26a-4b1e-8433-e649fc0a71ec)'
    commandOptions: -input=false -var "client_id=$(TF_VAR_client_id) client_secret=$(TF_VAR_client_secret) subscription_id=$(TF_VAR_subscription_id) tenant_id=$(TF_VAR_tenant_id)"